server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
    autoconfigure:
      exclude:
        - "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"
  application:
    name: "poc"
  devtools:
    add-properties: false
  datasource:
    # H2 database configuration.
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/demo.h2.db
    username: admin
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop


